default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: osm_app_development

test:
  <<: *default
  database: osm_app_test

production:
  <<: *default
  database: osm_app_production
  username: osm_app
  password: <%= ENV["OSM_APP_DATABASE_PASSWORD"] %>
